name: l10n_generator
description: A sample command-line application.
version: 0.0.1
author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  collection: ^1.15.0-nullsafety.4
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.8
